### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by darealshinji**
I have rewritten the Makefile a bit. It's basically the same as before, but with `$(CFLAGS) $(CPPFLAGS) $(LDFLAGS)` so that optional buildflags can be passed.

### CODE REVIEW

**Comment by PinkPandaKatie** [comment]
Are you also going to apply the same changes to Makefile.Win32? Don't worry about Makefile.NoMIDI, it hasn't been updated and should probably be deleted.

**Comment by darealshinji** [comment]
I didn't thought about it, but yes i can do this.

**Comment by darealshinji** [comment]
I've edited the Win32 Makefile, but I don't have a Cygwin installation to test it.

**Comment by PinkPandaKatie** [comment]
I've merged the request, and made a few changes:
1. Instead of using $(wildcard *.c), I explicitly added the sources to the makefile since I have some other test C files in my working directory
2. In the Win32 makefile, SDL_CFLAGS was not being set because the previous line ended with a backslash, causing make to continue that line. This was mostly my fault, I never noticed it before because I always overrode the MINGW_PATH and PREFIX variables (since I cross-compile).

You don't actually need Cygwin to compile, only MinGW (compiling with cygwin creates a runtime dependency on the cygwin libraries). You can install MinGW on Linux for cross-compiling by running:

```
sudo apt-get install mingw-w64
```

which will install in /usr/i686-w64-mingw32 and /usr/x86_64-w64-mingw32.

**Pull request merged**
